// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojycvpkerurueidqmmdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qeWN2cGtlcnVydWVpZHFtbWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNzE0MjEsImV4cCI6MjA0OTg0NzQyMX0.i-dSB9a0SsWTUjHq8oPDHERbZ6pp7V2xcCoBdlLmjzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);